services:
  - type: web
    name: price-bot
    env: python
    plan: free
    pythonVersion: 3.11.9  
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python price_bot.py"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false