services:
  - type: web
    name: price-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python price_bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: TELEGRAM_BOT_TOKEN
        sync: false