services:
  - type: worker
    name: price-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python price_bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # set via Render dashboard
